// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/aeramu/menfess-backend/entity"
	mock "github.com/stretchr/testify/mock"
)

// AuthModule is an autogenerated mock type for the AuthModule type
type AuthModule struct {
	mock.Mock
}

// ComparePassword provides a mock function with given fields: ctx, hash, password
func (_m *AuthModule) ComparePassword(ctx context.Context, hash string, password string) error {
	ret := _m.Called(ctx, hash, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, hash, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateToken provides a mock function with given fields: ctx, user
func (_m *AuthModule) GenerateToken(ctx context.Context, user entity.User) (string, error) {
	ret := _m.Called(ctx, user)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, entity.User) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
