// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LogModule is an autogenerated mock type for the LogModule type
type LogModule struct {
	mock.Mock
}

// Log provides a mock function with given fields: err, payload, message
func (_m *LogModule) Log(err error, payload interface{}, message string) {
	_m.Called(err, payload, message)
}
