// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/aeramu/menfess-backend/entity"
	mock "github.com/stretchr/testify/mock"
)

// PostModule is an autogenerated mock type for the PostModule type
type PostModule struct {
	mock.Mock
}

// FindPostByID provides a mock function with given fields: ctx, id, userID
func (_m *PostModule) FindPostByID(ctx context.Context, id string, userID string) (*entity.Post, error) {
	ret := _m.Called(ctx, id, userID)

	var r0 *entity.Post
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.Post); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
